name: Go

on:
  push:
    branches: [ v*, dev ]
  pull_request:
    branches: [ v*, dev ]

jobs:
  # Test
  tests:
    name: Run tests on ${{ matrix.os }} ${{ matrix.go }}

    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
        go:
          - '1.16'
          - '1.17'
          - '1.18'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -v -race ./...

  # Link
  lint:
    name: Test with go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.16
          - 1.17
          - 1.18
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45
      - run: go test -v ./...

  # Build
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.go }} for GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}

    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
        go:
          - '1.16'
          - '1.17'
          - '1.18'
        goos:
          - 'linux'
          - 'android'
          - 'darwin'
          - 'freebsd'
          - 'openbsd'
          - 'windows'
        goarch:
          - 'amd64'

        exclude:
          - os: ubuntu-latest
            goos: darwin

          - os: windows-latest
            goos: darwin

        include:
          - os: ubuntu-latest
            goos: linux
            goarch: arm64

          - os: ubuntu-latest
            goos: linux
            goarch: ppc64le

          - os: ubuntu-latest
            goos: android
            goarch: arm64

          - os: ubuntu-latest
            goos: openbsd
            goarch: arm64

    runs-on: ${{ matrix.os }}

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .
